### ISSUE TITLE
Segfault on startup

### ISSUE THREAD

**Issue by fabiansvara** [knossos-project/knossos#238]
Unfortunately I can't seem to find a way to obtain the core dump generated in juju...

svara@fabian:~/knossos-gh/knossos/build$ ./knossos 
[:0] 	Debug: Error reading config file at path:knossos.conf
[:0] 	Debug: could not open »stdOverlay.lut«
[:0] 	Debug: could not open »stdOverlay.lut«
[:0] 	Warning: QOpenGLWidget: Cannot make uninitialized widget current
[:0] 	Warning: QOpenGLWidget: Cannot make uninitialized widget current
[:0] 	Warning: QOpenGLWidget: Cannot make uninitialized widget current
[:0] 	Debug: 2.1.2 NVIDIA 304.125
[:0] 	Debug: Reading Tree LUT at default.lut

[:0] 	Debug: Unable to open Tree LUT at default.lut.
[:0] 	Debug: entered load tree LUT fallback
[:0] 	Warning: QOpenGLShader::compile(Vertex): failed
[:0] 	Warning: QOpenGLShader::compile(Fragment): failed
[:0] 	Warning: bool QOpenGLTextureBlitter::create() Could not link shader program:
 ""
Segmentation fault (core dumped)

**Comment by fabiansvara** [comment]
gdb output

[New Thread 0x7fffd52f1700 (LWP 17656)]
[New Thread 0x7fffd5cf7700 (LWP 17655)]
[New Thread 0x7fffd64f8700 (LWP 17654)]
[New Thread 0x7fffdd250700 (LWP 17653)]
[New Thread 0x7fffd7fff700 (LWP 17645)]
[New Thread 0x7fffdea3d700 (LWP 17638)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffef54cca2 in __memmove_ssse3_back () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007fffef54cca2 in __memmove_ssse3_back () from /usr/lib/libc.so.6
#1  0x00007ffff520f936 in ?? () from /usr/lib/libGL.so.1
#2  0x00007ffff521287f in ?? () from /usr/lib/libGL.so.1
#3  0x00007ffff0f34530 in ?? () from /usr/lib/libQt5Gui.so.5
#4  0x00007ffff0e9ac0a in QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, QOpenGLContext*, bool) ()
   from /usr/lib/libQt5Gui.so.5
#5  0x00007fffe0c26d97 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#6  0x00007ffff11ac8fb in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff11ad7b5 in ?? () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff11aef70 in ?? () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff11afac6 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff11ff703 in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff11a1acc in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff11a6f10 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff08b9d1b in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff0bea646 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () from /usr/lib/libQt5Gui.so.5
#15 0x00007ffff0beb37d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#16 0x00007ffff0bd01ef in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#17 0x00007fffe0c3a1d0 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#18 0x00007fffe9eaca0d in g_main_context_dispatch ()
   from /usr/lib/libglib-2.0.so.0
#19 0x00007fffe9eaccf8 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007fffe9eacdac in g_main_context_iteration ()
   from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff0912077 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007ffff08b77b2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00000000004a8542 in blockDownloadExtractData(QNetworkReply&) ()
#24 0x00000000004a8bed in Network::refresh(QUrl const&) ()
#25 0x00000000004dea6c in Knossos::findAndRegisterAvailableDatasets() ()

**Comment by fabiansvara** [comment]
Backtrace without existing config:

(gdb) bt
#0  0x00007fffef54cca2 in __memmove_ssse3_back () from /usr/lib/libc.so.6
#1  0x00007ffff520f936 in ?? () from /usr/lib/libGL.so.1
#2  0x00007ffff521287f in ?? () from /usr/lib/libGL.so.1
#3  0x00007ffff0f34530 in ?? () from /usr/lib/libQt5Gui.so.5
#4  0x00007ffff0e9ac0a in QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, QOpenGLContext*, bool) () from /usr/lib/libQt5Gui.so.5
#5  0x00007fffe0c26d97 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#6  0x00007ffff11ac8fb in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007ffff11ad7b5 in ?? () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff11aef70 in ?? () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff11afac6 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff11ff703 in ?? () from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff11a1acc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff11a6f10 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff08b9d1b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#14 0x00007ffff0bea646 in QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) () from /usr/lib/libQt5Gui.so.5
#15 0x00007ffff0beb37d in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#16 0x00007ffff0bd01ef in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#17 0x00007fffe0c3a1d0 in ?? () from /usr/lib/qt/plugins/platforms/libqxcb.so
#18 0x00007fffe9eaca0d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007fffe9eaccf8 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007fffe9eacdac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#21 0x00007ffff0912077 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007ffff08b77b2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00007ffff08bf18c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#24 0x000000000045faac in main ()
(gdb)

**Comment by fabiansvara** [comment]
This was introduced in d6c02e5.
Might therefore depend on GL system libraries installed in juju (or whatever system the user has...).

**Comment by fabiansvara** [comment]
This was caused by a version mismatch of the nvidia driver installed on the system and the Nvidia GL libraries installed in juju.
